### ISSUE TITLE
How to refresh data? Is this controlled component?

### ISSUE THREAD

**Issue by waltermvp** [hongkouHenk/react-native-expo-interactive-section-list#3]
I hate to bother again, however after I modify the state of my sectioned items the UI does not refresh with the updated information. 
Is there a way to force a refresh of a specific cell? 

currently, I am just setting my sectionedItems to an empty array before refeching info. 
I'd love to help in any I can.

**Comment by waltermvp** [comment]
Amazing lib by the wy I love it :)

**Comment by hongkouHenk** [comment]
No worries. I've added a fix for this. I tested by setting the 'data' props with a data state array, which is set inside useEffect hook. This also makes it possible to modify state and see the updated item(s) reflected inside the SectionList. 

NOTE: I updated the component name to align it with the package name. You may need to make this change for import in your project too.

**Comment by waltermvp** [comment]
Great it works well now thanks!
